# standard jekyll configuration options
destination: public
exclude: ['CNAME', 'Rakefile', 'README.md', 'config.rb', 'public']
pygments: true

# configuration required for some pages

domain: blog.example.com
title: QuickDialog
author: Me
email: me@example.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

# github:
#   username: ghusername

# disqus:
#   id: disqusid
